version: "3"

services:
  stable-diffusion-webui:
    image: darknightlab/stable-diffusion-webui-docker:latest
    # build: .
    container_name: stable-diffusion-webui
    restart: always
    command: []
    environment:
      - COMMANDLINE_ARGS=--listen --port 7860 --xformers --enable-insecure-extension-access
    ports:
      - "7860:7860"
    volumes:
      - ../data/models:/home/diffusion/stable-diffusion-webui/models
      - ../data/outputs:/home/diffusion/stable-diffusion-webui/outputs
      - ../config:/home/diffusion/stable-diffusion-webui/config
      - ../data/cache:/home/diffusion/.cache
      - ../data/extensions:/home/diffusion/stable-diffusion-webui/extensions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
