version: "3"

services:
  stable-diffusion-webui:
    image: stable-diffusion-webui
    build: .
    container_name: stable-diffusion-webui
    restart: always
    command: []
    environment:
      - COMMANDLINE_ARGS=--listen --port 7860
    ports:
      - "7860:7860"
    volumes:
      - ../data/log:/home/diffusion/stable-diffusion-webui/log
      - ../data/models:/home/diffusion/stable-diffusion-webui/models
      - ../data/outputs:/home/diffusion/stable-diffusion-webui/outputs
      - ../config:/home/diffusion/stable-diffusion-webui/config
      - ../data/cache:/home/diffusion/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
